Class Throw2
    Sub test()
	If False then Throw New System.Exception
    End Sub
End Class